// Generated by scripts/gen-artifacts.mjs from the Foundry build. Do not edit by hand.
//
// Run `npm run gen` after changing anything in evm/src. The parity test regenerates this in
// memory and fails if the committed copy has drifted, so an edit here is a test failure rather
// than a quiet disagreement between the SDK and the chain.

/**
 * Every error `HyperionErrors.sol` declares, in declaration order.
 *
 * The order is load bearing: `errors.ts` keeps the same list by hand so the human readable help
 * can live next to it, and the parity test compares the two.
 */
export const GENERATED_EVM_ERROR_NAMES = [
  "AlreadyInitialized",
  "NotInitialized",
  "Unauthorized",
  "NotRailReceiver",
  "RouteDisabled",
  "AdapterNotSet",
  "InvalidAmount",
  "AmountNotRepresentable",
  "DecimalOverflow",
  "InvalidDecimals",
  "SlippageExceeded",
  "FeeTooHigh",
  "AmountBelowMinimum",
  "FlowLimitExceeded",
  "InvalidLimit",
  "InvalidWindow",
  "LimitNotRaised",
  "InvalidDestination",
  "ZeroAddressKey",
  "MuxedNotSupported",
  "NotEvmAddress",
  "UnknownChain",
  "ReplayedMessage",
  "MalformedMessage",
  "UnsupportedHookVersion",
  "UnsupportedMessageVersion",
  "WrongDomain",
  "NotMintRecipient",
  "UnexpectedRailContract",
  "NothingMinted",
  "UnsupportedRoute",
  "TimelockNotQueued",
  "TimelockNotReady",
  "TimelockExpired",
  "TimelockDelayOutOfRange",
  "TimelockAlreadyExecuted",
  "ActionFieldNotEmpty",
  "ClaimNotFound",
  "ClaimAlreadySettled",
  "RecipientNotReady",
  "TokenNotRegistered",
  "TokenDisabled",
  "TokenNotMapped",
  "RailNotConfigured",
  "AlreadyConfigured",
  "ProtectedAsset",
  "ZeroAddress",
  "RefundFailed",
] as const;

/** Four byte selector to error, for every error the compiled contracts can actually revert with. */
export const EVM_ERROR_SELECTORS = {
  "0x0455eeee": { name: "ClaimNotFound", signature: "ClaimNotFound()" },
  "0x05a1a5df": { name: "UnknownChain", signature: "UnknownChain()" },
  "0x118cdaa7": { name: "OwnableUnauthorizedAccount", signature: "OwnableUnauthorizedAccount(address)" },
  "0x11b61b6a": { name: "AlreadyConfigured", signature: "AlreadyConfigured()" },
  "0x16509b9a": { name: "MalformedMessage", signature: "MalformedMessage()" },
  "0x17d0b6db": { name: "RouteDisabled", signature: "RouteDisabled()" },
  "0x1931ea85": { name: "TokenDisabled", signature: "TokenDisabled()" },
  "0x1e4fbdf7": { name: "OwnableInvalidOwner", signature: "OwnableInvalidOwner(address)" },
  "0x259ba1ad": { name: "TokenNotRegistered", signature: "TokenNotRegistered()" },
  "0x276f9a65": { name: "ZeroAddressKey", signature: "ZeroAddressKey()" },
  "0x2c5211c6": { name: "InvalidAmount", signature: "InvalidAmount()" },
  "0x392334ed": { name: "InvalidWindow", signature: "InvalidWindow()" },
  "0x3ee5aeb5": { name: "ReentrancyGuardReentrantCall", signature: "ReentrancyGuardReentrantCall()" },
  "0x44b39ad8": { name: "ClaimAlreadySettled", signature: "ClaimAlreadySettled()" },
  "0x44e23f21": { name: "ActionFieldNotEmpty", signature: "ActionFieldNotEmpty()" },
  "0x469eb53c": { name: "ReplayedMessage", signature: "ReplayedMessage()" },
  "0x5274afe7": { name: "SafeERC20FailedOperation", signature: "SafeERC20FailedOperation(address)" },
  "0x6697b232": { name: "AccessControlBadConfirmation", signature: "AccessControlBadConfirmation()" },
  "0x71c4efed": { name: "SlippageExceeded", signature: "SlippageExceeded(uint256,uint256)" },
  "0x72942d97": { name: "TimelockNotReady", signature: "TimelockNotReady(uint64)" },
  "0x768fade0": { name: "TimelockExpired", signature: "TimelockExpired(uint64)" },
  "0x78c488a4": { name: "RecipientNotReady", signature: "RecipientNotReady()" },
  "0x7f356a63": { name: "RailNotConfigured", signature: "RailNotConfigured()" },
  "0x828d5663": { name: "TokenNotMapped", signature: "TokenNotMapped()" },
  "0x82b42900": { name: "Unauthorized", signature: "Unauthorized()" },
  "0x87afb842": { name: "MuxedNotSupported", signature: "MuxedNotSupported()" },
  "0x88bb59d2": { name: "UnsupportedHookVersion", signature: "UnsupportedHookVersion()" },
  "0x8dfc202b": { name: "ExpectedPause", signature: "ExpectedPause()" },
  "0x9289bf61": { name: "LimitNotRaised", signature: "LimitNotRaised()" },
  "0x9d7a7801": { name: "AmountNotRepresentable", signature: "AmountNotRepresentable()" },
  "0xa091855e": { name: "AdapterNotSet", signature: "AdapterNotSet()" },
  "0xa1d40c9a": { name: "DecimalOverflow", signature: "DecimalOverflow()" },
  "0xac6b05f5": { name: "InvalidDestination", signature: "InvalidDestination()" },
  "0xb3c237e0": { name: "UnexpectedRailContract", signature: "UnexpectedRailContract()" },
  "0xcc3da7e0": { name: "TimelockDelayOutOfRange", signature: "TimelockDelayOutOfRange()" },
  "0xcd4e6167": { name: "FeeTooHigh", signature: "FeeTooHigh()" },
  "0xd25598a0": { name: "InvalidDecimals", signature: "InvalidDecimals()" },
  "0xd92e233d": { name: "ZeroAddress", signature: "ZeroAddress()" },
  "0xd93c0665": { name: "EnforcedPause", signature: "EnforcedPause()" },
  "0xdf359a15": { name: "FlowLimitExceeded", signature: "FlowLimitExceeded(uint256,uint256)" },
  "0xdfc44acf": { name: "TimelockNotQueued", signature: "TimelockNotQueued()" },
  "0xe2517d3f": { name: "AccessControlUnauthorizedAccount", signature: "AccessControlUnauthorizedAccount(address,bytes32)" },
  "0xe55fb509": { name: "InvalidLimit", signature: "InvalidLimit()" },
  "0xe93a7ad0": { name: "NotRailReceiver", signature: "NotRailReceiver()" },
  "0xf0c49d44": { name: "RefundFailed", signature: "RefundFailed()" },
  "0xf6432eb1": { name: "TimelockAlreadyExecuted", signature: "TimelockAlreadyExecuted()" },
} as const;

export type EvmErrorSelector = keyof typeof EVM_ERROR_SELECTORS;

/**
 * Name an error from the first four bytes of revert data.
 *
 * Returns null rather than throwing for anything it does not recognise, because unrecognised
 * revert data is the normal case when a call lands in a token or a rail rather than in Hyperion.
 */
export function errorNameFromSelector(selector: string): string | null {
  const lowered = selector.toLowerCase();
  const hit = (EVM_ERROR_SELECTORS as Record<string, { name: string } | undefined>)[lowered];
  return hit?.name ?? null;
}

/** Pull the selector off revert data and name it, when there is enough data to have one. */
export function errorNameFromRevert(data: string): string | null {
  if (!data.startsWith("0x") || data.length < 10) return null;
  return errorNameFromSelector(data.slice(0, 10));
}
