// Generated by scripts/gen-artifacts.mjs from the Foundry build. Do not edit by hand.
//
// Run `npm run gen` after changing anything in evm/src. The parity test regenerates this in
// memory and fails if the committed copy has drifted, so an edit here is a test failure rather
// than a quiet disagreement between the SDK and the chain.

/** The compiled ABI of `IRailAdapter`. */
export const railAdapterAbi = [
  {
    "type": "function",
    "name": "dispatch",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "destination",
        "type": "tuple",
        "internalType": "struct Destination",
        "components": [
          {
            "name": "chain",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "strkey",
            "type": "string",
            "internalType": "string"
          }
        ]
      },
      {
        "name": "nonce",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "railRef",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "quoteFee",
    "inputs": [
      {
        "name": "chain",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "route",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum RouteKind"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "supportsChain",
    "inputs": [
      {
        "name": "chain",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  }
] as const;
