[workspace]
resolver = "2"
members = [
    "crates/hyperion-core",
    "crates/hyperion-router",
    "crates/hyperion-adapter-cctp",
    "crates/hyperion-adapter-axelar",
    "crates/hyperion-adapter-allbridge",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/StellarHyperion/stellarhyperion-contracts"
rust-version = "1.85"

[workspace.dependencies]
soroban-sdk = "28.0.0"
hyperion-core = { path = "crates/hyperion-core" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
